<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>91084d21-4682-4f16-bb5b-9ecf27657782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[1]/div[1]/div[2]/div/div[1]/div/div[1]/div/div/div[4]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>3814891e-c484-43e4-bdb0-a4df20285b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c7dff608-28e1-4f2d-b9d9-3747404bf646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>e9f5329a-bd89-4edb-8a9e-86f7488c9796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>d92fef04-7c64-4458-8a24-0aff78f7711b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-cxpSdN htzDJS&quot;]/div[@class=&quot;MuiBox-root-264 jss265&quot;]/div[@class=&quot;MuiBox-root-264 jss266&quot;]/div[@class=&quot;jss260&quot;]/div[@class=&quot;jss261&quot;]/div[@class=&quot;MuiBox-root-264 jss297&quot;]/div[@class=&quot;jss298&quot;]/div[@class=&quot;jss299&quot;]/button[@class=&quot;MuiButtonBase-root-343 MuiIconButton-root-335 jss300  MuiIconButton-sizeSmall-341&quot;]/span[@class=&quot;MuiIconButton-label-342&quot;]/svg[@class=&quot;MuiSvgIcon-root-326 jss301&quot;]/circle[1]</value>
      <webElementGuid>8f4652f8-7fcb-4181-8a18-db4d423d5db8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
