<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Work order has been created successfully</name>
   <tag></tag>
   <elementGuidId>2f595e5f-4476-4da0-8bbf-370657f73ed6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/div/div/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d83e626-1a7f-42e6-98a1-0702dfda2ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work order has been created successfully.</value>
      <webElementGuid>77886be8-6841-470d-9c59-b214c4834e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;khjoz4lra&quot;)/div[@class=&quot;Toastify__toast-body&quot;]/div[2]</value>
      <webElementGuid>32bcc4a4-5761-4e39-b0ca-d2876aaac4d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='khjoz4lra']/div/div[2]</value>
      <webElementGuid>4c9315b2-0a79-4ee7-8d75-71c959ddb44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Measurement'])[1]/following::div[23]</value>
      <webElementGuid>6caffb84-7702-454b-83a4-2ff33afb052b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esri'])[1]/following::div[33]</value>
      <webElementGuid>fcfcf5e7-60ec-4478-bae1-1600d903e0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work order creation email has been sent sucessfully.'])[1]/preceding::div[3]</value>
      <webElementGuid>4f6bacc6-e4ea-4034-9840-eba459b29957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[7]</value>
      <webElementGuid>02a95288-b819-4bbe-b200-a834ff963fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work order has been created successfully.']/parent::*</value>
      <webElementGuid>310e78bd-4130-4a2c-883f-72ef858eb6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]</value>
      <webElementGuid>ba784553-b549-419b-ad48-02db0b491837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Work order has been created successfully.' or . = 'Work order has been created successfully.')]</value>
      <webElementGuid>5dde3a7f-765c-4a4c-8c26-22696c04e7c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
