<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search_rail-icon</name>
   <tag></tag>
   <elementGuidId>c3ccd418-46b5-4026-b037-484c7817c1a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rail-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78c9d940-6c5f-4b72-b0a5-cbf3618223b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>f5966a5f-c18e-4ab3-b4c8-3b3ba4b3b5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/png/layerList.png</value>
      <webElementGuid>d6dadcd4-6408-45ea-82d8-8da7f745298c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>2686d521-7a23-4c84-926d-6caaf810b8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bYoBSM dTkzZR&quot;]/div[@class=&quot;sc-kLwhqv ktAtLc&quot;]/div[@class=&quot;sc-fKVqWL cmLhtH&quot;]/div[@class=&quot;sc-egiyK eiYbNk&quot;]/div[3]/div[@class=&quot;sc-hBUSln gDLFVM widget&quot;]/div[@class=&quot;sc-fotOHu wfUoZ icoWrap&quot;]/img[@class=&quot;rail-icon&quot;]</value>
      <webElementGuid>6b2e664a-7b4c-43a7-a3ce-fd4a5cc430fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/img</value>
      <webElementGuid>dd370ea6-ec05-4537-ac6a-17f6a9d9b179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon']</value>
      <webElementGuid>2df6f87a-e11e-4d7e-80bb-8cb878440f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>87b956b8-0b17-4f33-a7d2-b261505aac5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/png/layerList.png' and @alt = 'icon']</value>
      <webElementGuid>c22f4fb8-5109-44bd-a5c8-f485b099ccf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
