<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_System_img</name>
   <tag></tag>
   <elementGuidId>62a4de90-673f-4bf4-9f8f-c0b8624e051e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='simple-tabpanel-0']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6bf673e-8762-4512-8321-631f0dbef2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dde9523a-6087-418f-8348-5c7700c9f470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-tabpanel-0&quot;)/div[@class=&quot;MuiBox-root jss59&quot;]/div[@class=&quot;sc-jJoQJp eMPfTV&quot;]/div[@class=&quot;img&quot;]</value>
      <webElementGuid>7cd10a51-8d18-4204-af3b-969bbbc5cdd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simple-tabpanel-0']/div/div/div</value>
      <webElementGuid>4a3017fa-1c16-4ff8-b73c-47649558ca61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>8630e78f-5bf7-4f6c-9887-6345dd034105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
