<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quantity_MuiInputBase-input-2592 MuiI_2bc7ad</name>
   <tag></tag>
   <elementGuidId>9da0e5f4-8500-4bc0-b098-a829ef192cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sidebar-panel&quot;]/div[2]/div/div[1]/div[15]/div/div[1]/div[3]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root-2584.MuiInput-root-2573.MuiInput-underline-2576.Mui-focused.Mui-focused.MuiInputBase-formControl-2585.MuiInput-formControl-2574 > input.MuiInputBase-input-2592.MuiInput-input-2580</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f352d00-6e7d-4e02-94b7-56e2fd1ab1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6d7d03f-5d1f-4a3e-b80a-494bde13e307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9ef4056e-0918-43b7-a1c0-69e90faa65c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c6f1e630-3f6d-4615-89d7-afacaf12feae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-2592 MuiInput-input-2580</value>
      <webElementGuid>803cf191-026a-461c-abf7-78cbb1ac8217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd3b6339-3fbf-472b-9312-076f3af8d3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-cxpSdN htzDJS&quot;]/div[@class=&quot;MuiBox-root-2460 jss2461&quot;]/div[@class=&quot;MuiBox-root-2460 jss2462&quot;]/div[@class=&quot;MuiBox-root-2460 jss2703&quot;]/div[@class=&quot;MuiBox-root-2460 jss2708&quot;]/div[@class=&quot;MuiBox-root-2460 jss2709&quot;]/div[@class=&quot;MuiFormControl-root-2533&quot;]/div[@class=&quot;MuiFormControl-root-2533 MuiTextField-root-2560&quot;]/div[@class=&quot;MuiInputBase-root-2584 MuiInput-root-2573 MuiInput-underline-2576 Mui-focused Mui-focused MuiInputBase-formControl-2585 MuiInput-formControl-2574&quot;]/input[@class=&quot;MuiInputBase-input-2592 MuiInput-input-2580&quot;]</value>
      <webElementGuid>326f2732-a714-41c2-ae2d-01c5aeb61d80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1']</value>
      <webElementGuid>f93b6564-93fe-4e23-be85-46b1cb05777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[23]/div/div/div[3]/div/div/input</value>
      <webElementGuid>fc827af9-3fa5-4f7b-9244-32849be74f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>960375a5-888d-4136-a053-b7e5d64b5535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number']</value>
      <webElementGuid>96de83d0-d76b-4c43-a4ee-eb919c1c9378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
