<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select Assignee_assignee-autocomplete</name>
   <tag></tag>
   <elementGuidId>e28dbe2a-314c-40d5-ad90-5fee67228956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='assignee-autocomplete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#assignee-autocomplete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f8d40e2-b504-4a18-99ce-002cb2213418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5382af4f-fcb8-43c8-bfac-c849dbd4adef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b6ea92c-e938-4ca8-88fc-dd136043a2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assignee-autocomplete</value>
      <webElementGuid>f0d778d2-f81f-4897-b7ef-22a61c29be78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Assignee</value>
      <webElementGuid>7246ecc2-a1ed-4d6f-84fe-9082769e1faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>167e8e54-3f6f-4546-a75c-703c2848c2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-760 MuiInput-input-748 MuiAutocomplete-input-712 MuiAutocomplete-inputFocused-713 MuiInputBase-inputAdornedEnd-765</value>
      <webElementGuid>d76ec9cb-56f3-4ee0-ad43-d77b4719fee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>42ad4c19-0373-4b6e-bd80-083d7eda8c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>16d37b96-9cf5-4f73-ad0b-fcccdc7264a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db96d6d9-c42a-49a0-b01f-b97ed2c90372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>assignee-autocomplete-popup</value>
      <webElementGuid>9110776f-bd86-46a8-8334-3a82c0993a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignee-autocomplete&quot;)</value>
      <webElementGuid>c3403ad4-fe20-4c85-9bdb-bba8a73d2dd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='assignee-autocomplete']</value>
      <webElementGuid>3d255649-3a9d-4d2a-b842-ea087d9e9a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>5e8a3636-2b0f-4dde-9991-433953c1b72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>0d155168-b868-4790-a62a-7bb2baaffcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'assignee-autocomplete' and @placeholder = 'Select Assignee' and @type = 'text']</value>
      <webElementGuid>b15656f7-bf26-4376-b5a2-d51568f76107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
