<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Statement Field Test_equipment</name>
   <tag></tag>
   <elementGuidId>c20563a9-2311-4e89-bacf-d11fc723e353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='equipment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;equipment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e16bf6d-d13f-42c1-b4b6-5f39268d7961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2512 MuiSwitch-input-2506</value>
      <webElementGuid>67eba04b-08f4-46b0-9125-a9abd4025dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>equipment</value>
      <webElementGuid>961ba41d-e5c7-4ecc-a730-8bdfd90599a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5e94423d-357d-465e-bc78-9c643d19847c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-cxpSdN htzDJS&quot;]/div[@class=&quot;MuiBox-root-2460 jss2461&quot;]/div[@class=&quot;MuiBox-root-2460 jss2462&quot;]/div[@class=&quot;MuiBox-root-2460 jss2703&quot;]/label[@class=&quot;MuiFormControlLabel-root-2494 MuiFormControlLabel-labelPlacementStart-2495&quot;]/span[@class=&quot;MuiSwitch-root-2499&quot;]/span[@class=&quot;MuiButtonBase-root-2521 MuiIconButton-root-2513 jss2509 MuiSwitch-switchBase-2502 MuiSwitch-colorPrimary-2503&quot;]/span[@class=&quot;MuiIconButton-label-2520&quot;]/input[@class=&quot;jss2512 MuiSwitch-input-2506&quot;]</value>
      <webElementGuid>6f3ad3fe-aa47-4b76-a581-2481d8c91402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='equipment']</value>
      <webElementGuid>e36aa549-204f-49ce-ac72-8b1c7f76f8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[23]/label/span/span/span/input</value>
      <webElementGuid>d6cc903f-9f0a-4638-86c9-a028740d8dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/label/span/span/span/input</value>
      <webElementGuid>a7800ff3-c4ec-4924-8f5e-ff4ffac8b3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'equipment' and @type = 'checkbox']</value>
      <webElementGuid>fcb9cfbd-0129-483a-a05f-19ff24982a9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
