<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Item_material</name>
   <tag></tag>
   <elementGuidId>91c76de1-04be-4f16-b32b-5588552b2d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='material']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;material&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2feaf8f-858f-42b7-866f-b9728a00cd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2512 MuiSwitch-input-2506</value>
      <webElementGuid>c7dbeaf7-0c5f-4af6-af90-a6ff6ad48f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>material</value>
      <webElementGuid>54af28e1-b6f4-40a4-a06b-1eb35ac0baf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>05f97022-f90d-4a35-b78f-38e42f3e59ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-cxpSdN htzDJS&quot;]/div[@class=&quot;MuiBox-root-2460 jss2461&quot;]/div[@class=&quot;MuiBox-root-2460 jss2462&quot;]/div[@class=&quot;MuiBox-root-2460 jss2704&quot;]/label[@class=&quot;MuiFormControlLabel-root-2494 MuiFormControlLabel-labelPlacementStart-2495&quot;]/span[@class=&quot;MuiSwitch-root-2499&quot;]/span[@class=&quot;MuiButtonBase-root-2521 MuiIconButton-root-2513 jss2509 MuiSwitch-switchBase-2502 MuiSwitch-colorPrimary-2503&quot;]/span[@class=&quot;MuiIconButton-label-2520&quot;]/input[@class=&quot;jss2512 MuiSwitch-input-2506&quot;]</value>
      <webElementGuid>523370d2-80f3-43c1-ab61-76f7e3804dc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='material']</value>
      <webElementGuid>1cc4b952-136e-4223-91f9-dc42987a0a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[24]/label/span/span/span/input</value>
      <webElementGuid>8834b11d-d272-469b-80b5-dbca8b6cf28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/label/span/span/span/input</value>
      <webElementGuid>915234d9-2927-4837-8f2f-0c64feedc3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'material' and @type = 'checkbox']</value>
      <webElementGuid>081e6f03-895d-4977-b959-3d1f1f3b7889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
