<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_MuiInputBase-input-2592 MuiInput_7ee47b</name>
   <tag></tag>
   <elementGuidId>f36e38d0-49a0-4314-9d12-83ef4d817fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Ton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root-2460.jss2709 > div.MuiFormControl-root-2533 > div.MuiFormControl-root-2533.MuiTextField-root-2560 > div.MuiInputBase-root-2584.MuiInput-root-2573.MuiInput-underline-2576.Mui-disabled.Mui-disabled.MuiInputBase-formControl-2585.MuiInput-formControl-2574 > input.MuiInputBase-input-2592.MuiInput-input-2580.Mui-disabled.Mui-disabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42165613-d0c9-4bf8-94a5-74865a58eee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4e3fba13-c239-470d-a9ae-ac56457017c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ec382ba-71bc-494e-bce5-d22668af94b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input-2592 MuiInput-input-2580 Mui-disabled Mui-disabled</value>
      <webElementGuid>4e3a3f16-0766-47b4-b182-829ec1cc470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ton</value>
      <webElementGuid>f2f8be11-27fa-458f-b1be-26c7d2b469bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-cxpSdN htzDJS&quot;]/div[@class=&quot;MuiBox-root-2460 jss2461&quot;]/div[@class=&quot;MuiBox-root-2460 jss2462&quot;]/div[@class=&quot;MuiBox-root-2460 jss2703&quot;]/div[@class=&quot;MuiBox-root-2460 jss2708&quot;]/div[@class=&quot;MuiBox-root-2460 jss2709&quot;]/div[@class=&quot;MuiFormControl-root-2533&quot;]/div[@class=&quot;MuiFormControl-root-2533 MuiTextField-root-2560&quot;]/div[@class=&quot;MuiInputBase-root-2584 MuiInput-root-2573 MuiInput-underline-2576 Mui-disabled Mui-disabled MuiInputBase-formControl-2585 MuiInput-formControl-2574&quot;]/input[@class=&quot;MuiInputBase-input-2592 MuiInput-input-2580 Mui-disabled Mui-disabled&quot;]</value>
      <webElementGuid>8c2d8ad8-98ad-4ab4-8a8b-60e0c50be898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Ton']</value>
      <webElementGuid>ec40f334-717d-4155-9a76-29a542503c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[23]/div/div/div[2]/div/div/input</value>
      <webElementGuid>77db3dc3-814f-4823-bc69-a0ab9c70491e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>124a01a9-be3f-46ef-9a26-9ec380e52c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>2b260c40-a8a1-43d8-bc8d-30df4b830296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
