<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload_repeatingWorkOrder</name>
   <tag></tag>
   <elementGuidId>d1359254-c1a8-409a-915a-887cc98c7f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;repeatingWorkOrder&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='repeatingWorkOrder']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92e0b0d5-bc25-4096-81f6-8c47e8cb65af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss50 MuiSwitch-input</value>
      <webElementGuid>1d26b959-83f0-4802-ba1d-f319bed1eae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatingWorkOrder</value>
      <webElementGuid>a32e1c7d-42e8-42e2-9ede-e3107d686b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>812d8fe3-ff67-43c7-97c9-dc941f131914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-cxpSdN htzDJS&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;MuiBox-root jss63&quot;]/div[@class=&quot;MuiBox-root jss73&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementStart&quot;]/span[@class=&quot;MuiSwitch-root&quot;]/span[@class=&quot;MuiButtonBase-root MuiIconButton-root jss47 MuiSwitch-switchBase MuiSwitch-colorPrimary&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/input[@class=&quot;jss50 MuiSwitch-input&quot;]</value>
      <webElementGuid>3f169ef9-e32c-4150-8a72-cdeba19019d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='repeatingWorkOrder']</value>
      <webElementGuid>c1ef24f4-efda-4315-b741-7aee11776cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[13]/label/span/span/span/input</value>
      <webElementGuid>9aa8281f-3011-46c2-b233-84121576bf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/label/span/span/span/input</value>
      <webElementGuid>6e2e5f20-9ccc-420f-a668-09ed4579a83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'repeatingWorkOrder' and @type = 'checkbox']</value>
      <webElementGuid>507428d5-cd8f-4950-9cac-b0e05fb04764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
