<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Item_labor</name>
   <tag></tag>
   <elementGuidId>34ff8476-71e8-4d5d-812a-0bab985d868e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='labor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;labor&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce2a6f08-0fbe-4768-9180-66cb018417f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss2512 MuiSwitch-input-2506</value>
      <webElementGuid>42a99841-1655-4e8f-a5a7-36084196b8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>labor</value>
      <webElementGuid>cc7bde5d-7190-4dbc-a541-4507db562559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c127e166-dde9-4cbc-a353-52a682fd4008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-cxpSdN htzDJS&quot;]/div[@class=&quot;MuiBox-root-2460 jss2461&quot;]/div[@class=&quot;MuiBox-root-2460 jss2462&quot;]/div[@class=&quot;MuiBox-root-2460 jss2705&quot;]/label[@class=&quot;MuiFormControlLabel-root-2494 MuiFormControlLabel-labelPlacementStart-2495&quot;]/span[@class=&quot;MuiSwitch-root-2499&quot;]/span[@class=&quot;MuiButtonBase-root-2521 MuiIconButton-root-2513 jss2509 MuiSwitch-switchBase-2502 MuiSwitch-colorPrimary-2503&quot;]/span[@class=&quot;MuiIconButton-label-2520&quot;]/input[@class=&quot;jss2512 MuiSwitch-input-2506&quot;]</value>
      <webElementGuid>06385ec2-5491-403f-aa03-a43abb41c399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='labor']</value>
      <webElementGuid>cd3f9acf-01e0-4395-a29c-fd41364305c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[25]/label/span/span/span/input</value>
      <webElementGuid>684be3eb-ed5d-41d6-ba82-ddb2072888b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[25]/label/span/span/span/input</value>
      <webElementGuid>8bea9f79-9aef-40d7-adc4-b7f612ab65b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'labor' and @type = 'checkbox']</value>
      <webElementGuid>82b5d9de-16c7-4ba3-8f59-7b579e82960e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
