<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_12TH STREET CONNECTOR From CHESTNUT ST To MAGAZINE ST - 20476</name>
   <tag></tag>
   <elementGuidId>d38cfa66-40b6-4771-b380-f0c8fbabd49a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div[1]/div[1]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#asset-id-autocomplete-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a93a02d9-5024-4e0c-a30c-59b768a91b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8aee7a33-1e94-49bf-a1af-439fd17ba290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>892f10c9-f593-4c8e-8b52-d2956345bf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asset-id-autocomplete-option-0</value>
      <webElementGuid>51fc904e-97c5-4276-b41a-382fe1cf0a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b9d55492-adad-4b12-a88e-d96c21ff835e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>401d266f-cb04-42ce-a9a1-277c5efa7ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dc83443d-628e-41fb-8295-2cccc964e406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option-1380</value>
      <webElementGuid>35e6989c-3262-4cc7-a131-8e9d21f2c9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>27946477-2bfa-4eb0-bfa9-c5117ebf0635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12 - TYLER AVE From 31ST ST To 32ND ST</value>
      <webElementGuid>d032de38-7c42-4979-8dc1-fef4a914853b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asset-id-autocomplete-option-0&quot;)</value>
      <webElementGuid>acbde125-03a2-4eaa-bc2a-c8cb736e8c6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='asset-id-autocomplete-option-0']</value>
      <webElementGuid>01e8ba14-f10b-492a-a458-1f7a03c53814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='asset-id-autocomplete-popup']/li</value>
      <webElementGuid>e75087a9-a7f8-45f8-a707-fdcab1704cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Work Order'])[1]/following::li[1]</value>
      <webElementGuid>89d48fde-d16a-4190-88bf-7a89d43b97c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::li[1]</value>
      <webElementGuid>0287f45b-6b5b-41e9-9405-9ebe1c0c9dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12 - TYLER AVE From 31ST ST To 32ND ST']/parent::*</value>
      <webElementGuid>e847ff93-5fa0-4856-b1d7-0b0d3c4b3e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>d06a9b19-07ce-421b-8aca-ec158522c27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'asset-id-autocomplete-option-0' and (text() = '12 - TYLER AVE From 31ST ST To 32ND ST' or . = '12 - TYLER AVE From 31ST ST To 32ND ST')]</value>
      <webElementGuid>7303eb4e-eebe-484f-ab54-0961686b2f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
