<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Asphalt - 22</name>
   <tag></tag>
   <elementGuidId>5bba61f0-5b90-411b-9305-cf5101108ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.MuiButtonBase-root-2521.MuiListItem-root-2792.MuiMenuItem-root-2789.MuiMenuItem-gutters-2790.MuiListItem-gutters-2797.MuiListItem-button-2798</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[3]/ul/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@tabindex = '0' and (text() = 'Asphalt - $22' or . = 'Asphalt - $22')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>99ec464a-fdb8-4b9e-9fff-566ace0eaae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-2521 MuiListItem-root-2792 MuiMenuItem-root-2789 MuiMenuItem-gutters-2790 MuiListItem-gutters-2797 MuiListItem-button-2798</value>
      <webElementGuid>e0838f82-b402-4a89-8058-ab78e2ffc2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e85c3806-04b2-4731-a3f9-1cb1608ad2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c6bf211b-23f7-4628-ab9a-da0a77c9a4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8b48e411-8e46-4999-87fe-a00be03e01a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>4d7701c8-e54e-4934-8f92-cb9aa81dd9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asphalt - $22</value>
      <webElementGuid>f2880ef2-62dc-48bf-ab77-79cd663d0103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root-2757 MuiMenu-paper-2654 MuiPopover-paper-2657 MuiPaper-elevation8-2768 MuiPaper-rounded-2758&quot;]/ul[@class=&quot;MuiList-root-2785 MuiMenu-list-2655 MuiList-padding-2786&quot;]/li[@class=&quot;MuiButtonBase-root-2521 MuiListItem-root-2792 MuiMenuItem-root-2789 MuiMenuItem-gutters-2790 MuiListItem-gutters-2797 MuiListItem-button-2798&quot;]</value>
      <webElementGuid>186ab86b-9133-4d9d-b6bb-ef675f7d9c33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li</value>
      <webElementGuid>376aaec9-96b8-4b95-8b4f-dadc09a0d7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Work Order'])[1]/following::li[1]</value>
      <webElementGuid>06eff3a2-7a63-4a40-a8b8-e9c9acd83442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::li[1]</value>
      <webElementGuid>6ddc15af-851a-4a21-95ab-756122983719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Asphalt']/parent::*</value>
      <webElementGuid>5b1ef2bf-73b1-456e-b79c-105893734dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>b49396a0-5301-4172-9c11-73b738c29db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Asphalt - $22' or . = 'Asphalt - $22')]</value>
      <webElementGuid>5f6be7ee-2142-4fb5-9868-4a04b19360fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
