<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Bridge Inspection</name>
   <tag></tag>
   <elementGuidId>ba821fb4-456a-4e6f-8bd5-ecad5cec0c25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[3]/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>11dcb852-de1d-41f9-abc5-3f1f37ecd6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-187 MuiListItem-root-179 MuiMenuItem-root-251 MuiMenuItem-gutters-252 MuiListItem-gutters-184 MuiListItem-button-185</value>
      <webElementGuid>bf9a2259-98c1-4d41-aebc-96bd8db66934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>18c73d52-1fbf-432e-bb70-a7332ce070fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>77111f4e-8bb0-4b8a-8119-a302498c1b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bcdddea1-4f6e-4270-9e85-c47cc1c2ef48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>231</value>
      <webElementGuid>995505ac-974f-4feb-8819-2d726e5d7d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bridge Inspection</value>
      <webElementGuid>c5dfab02-24f5-4caa-ad59-4289b5b73036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root-223 MuiMenu-paper-152 MuiPopover-paper-155 MuiPaper-elevation8-234 MuiPaper-rounded-224&quot;]/ul[@class=&quot;MuiList-root-174 MuiMenu-list-153 MuiList-padding-175&quot;]/li[@class=&quot;MuiButtonBase-root-187 MuiListItem-root-179 MuiMenuItem-root-251 MuiMenuItem-gutters-252 MuiListItem-gutters-184 MuiListItem-button-185&quot;]</value>
      <webElementGuid>d0f20b7e-97a6-446c-bd5a-a6ee96b55e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li[2]</value>
      <webElementGuid>0208f587-31cf-4022-abe7-d41e80fc259d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Groups'])[3]/following::li[1]</value>
      <webElementGuid>119b0940-2cbb-493f-b8e2-e98bb87cd2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Work Order'])[1]/following::li[2]</value>
      <webElementGuid>e714e426-d744-4952-8228-1907828167b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pavement Pavers'])[1]/preceding::li[1]</value>
      <webElementGuid>60e38136-38ac-46ad-b3e4-eb5ae8f84b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bridge Inspection']/parent::*</value>
      <webElementGuid>3a00c98a-b1c9-45a0-aa8b-46a57dae8a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[2]</value>
      <webElementGuid>c7d4fc28-2f0a-467b-a460-1998812a85ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Bridge Inspection' or . = 'Bridge Inspection')]</value>
      <webElementGuid>1cc07071-fea8-4598-afd5-60f0e1777aff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
