<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_High</name>
   <tag></tag>
   <elementGuidId>ea1dc184-63d7-4723-b46a-023ea52e0f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[3]/ul/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e342b4e3-97f3-4894-a5a3-faa09c14455f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-1929 MuiListItem-root-2151 MuiMenuItem-root-2148 MuiMenuItem-gutters-2149 MuiListItem-gutters-2156 MuiListItem-button-2157</value>
      <webElementGuid>15f1e1ad-7274-42c4-90e9-a3cab3bb52f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9f2fb674-4709-4d08-84dc-6bcd4c6f2267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6ed18def-72ec-410a-b7de-131a66870cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85222ba7-8c38-49a5-874f-79e8a58457b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>High</value>
      <webElementGuid>e141324b-1680-4bcc-ac4f-f39025fd0d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>High</value>
      <webElementGuid>ed2a3ca6-eb41-41e9-8c60-ec3e85be906a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root-2116 MuiMenu-paper-2062 MuiPopover-paper-2065 MuiPaper-elevation8-2127 MuiPaper-rounded-2117&quot;]/ul[@class=&quot;MuiList-root-2144 MuiMenu-list-2063 MuiList-padding-2145&quot;]/li[@class=&quot;MuiButtonBase-root-1929 MuiListItem-root-2151 MuiMenuItem-root-2148 MuiMenuItem-gutters-2149 MuiListItem-gutters-2156 MuiListItem-button-2157&quot;]</value>
      <webElementGuid>b504d9fc-6cc3-491f-a6e4-7250c8aa4cc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li[2]</value>
      <webElementGuid>d55b51fd-fa2e-4f09-b6b4-02de69ece317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urgent'])[2]/following::li[1]</value>
      <webElementGuid>0d286816-56a1-450c-b499-eefe0af4a158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Work Order'])[1]/following::li[2]</value>
      <webElementGuid>940c0432-9fce-409d-80a7-c6b74dd19ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/preceding::li[1]</value>
      <webElementGuid>7b27e41c-bf05-442e-b0c2-98c7eb879615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[1]/preceding::li[2]</value>
      <webElementGuid>89ffb208-4a0f-4a6c-9318-c92f7513fb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='High']/parent::*</value>
      <webElementGuid>4e47882e-1539-46c6-acf1-1692f2048f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>50a2a3b5-7ae6-40e2-b485-84addcc4137b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'High' or . = 'High')]</value>
      <webElementGuid>e0ca8284-48a8-4b74-805f-5843e834a28e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
