<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Snow Plow - 15</name>
   <tag></tag>
   <elementGuidId>f95ad1c5-0722-442c-aa07-f244466c5601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[3]/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MuiButtonBase-root-2521.MuiListItem-root-2746.MuiMenuItem-root-2743.MuiMenuItem-gutters-2744.MuiListItem-gutters-2751.MuiListItem-button-2752</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b0020a23-49fc-4430-92e2-cec911f9256a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-2521 MuiListItem-root-2746 MuiMenuItem-root-2743 MuiMenuItem-gutters-2744 MuiListItem-gutters-2751 MuiListItem-button-2752</value>
      <webElementGuid>8ab46d16-c0ba-4b3e-bec0-3732552956c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0639e97b-893d-4b19-897c-0fb8d13821c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1222c51d-66b3-42e7-a636-bf1118535da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55a533a6-47c4-4a8c-ae13-9a9740423d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a1b2cbde-6fc0-4a83-8675-b454c44db322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Snow Plow - $15</value>
      <webElementGuid>6d22aad8-3e09-4797-8e50-0cbafa8001e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root-2711 MuiMenu-paper-2654 MuiPopover-paper-2657 MuiPaper-elevation8-2722 MuiPaper-rounded-2712&quot;]/ul[@class=&quot;MuiList-root-2739 MuiMenu-list-2655 MuiList-padding-2740&quot;]/li[@class=&quot;MuiButtonBase-root-2521 MuiListItem-root-2746 MuiMenuItem-root-2743 MuiMenuItem-gutters-2744 MuiListItem-gutters-2751 MuiListItem-button-2752&quot;]</value>
      <webElementGuid>0134c403-b3d5-4fbe-974f-6d5747143bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li</value>
      <webElementGuid>f024b570-0256-4705-9647-4080719000cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Work Order'])[1]/following::li[1]</value>
      <webElementGuid>7b41ae7d-9b92-46c0-a0dc-b0cbe5ff9ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::li[1]</value>
      <webElementGuid>b83e8b44-175d-4e38-8bfa-046aaff91a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Snow Plow']/parent::*</value>
      <webElementGuid>d6b82bc4-08c2-4fb6-90ce-01290c9c4b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>39e3a787-7d08-4004-8e17-acedafbbe3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Snow Plow - $15' or . = 'Snow Plow - $15')]</value>
      <webElementGuid>31f5e95d-5c8f-46cb-8111-2104a1080e2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
