<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Supervisor - 30</name>
   <tag></tag>
   <elementGuidId>2fac6c9d-a095-4f6c-985d-29bbbdcf58ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[6]/div[3]/ul/li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.MuiButtonBase-root-2521.MuiListItem-root-2838.MuiMenuItem-root-2835.MuiMenuItem-gutters-2836.MuiListItem-gutters-2843.MuiListItem-button-2844</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3f3d7849-0c26-4504-a258-62ab1f5038ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-2521 MuiListItem-root-2838 MuiMenuItem-root-2835 MuiMenuItem-gutters-2836 MuiListItem-gutters-2843 MuiListItem-button-2844</value>
      <webElementGuid>19edc1fe-cc70-499f-a11d-261e00b05edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b5a06b4-a87c-4d8e-a7a1-2634b33f14e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f9aaa2b0-5777-4447-b9ed-85be0b5413a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55590e9b-bd3e-4452-9d0d-5799efc50ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>75291c6d-cd98-4fe6-b1e4-57d6c572e3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Supervisor - $30</value>
      <webElementGuid>f45cb1b8-7552-4736-bcd7-7402a4c19280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-&quot;)/div[@class=&quot;MuiPaper-root-2803 MuiMenu-paper-2654 MuiPopover-paper-2657 MuiPaper-elevation8-2814 MuiPaper-rounded-2804&quot;]/ul[@class=&quot;MuiList-root-2831 MuiMenu-list-2655 MuiList-padding-2832&quot;]/li[@class=&quot;MuiButtonBase-root-2521 MuiListItem-root-2838 MuiMenuItem-root-2835 MuiMenuItem-gutters-2836 MuiListItem-gutters-2843 MuiListItem-button-2844&quot;]</value>
      <webElementGuid>5d558e27-e886-4df2-b89a-3983b3fdb3fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-']/div[3]/ul/li</value>
      <webElementGuid>611c3a3c-94df-402c-a9c8-45b572ed2fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Work Order'])[1]/following::li[1]</value>
      <webElementGuid>9f3a8826-c685-4418-b842-073f2cfb8d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::li[1]</value>
      <webElementGuid>9fa72f39-979a-4214-a9ae-f8431eb6fe49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Supervisor']/parent::*</value>
      <webElementGuid>c803dd13-d66f-4146-bbb1-87fc94b69b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>7486f5c4-dbeb-4222-b8b8-6545d837c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Supervisor - $30' or . = 'Supervisor - $30')]</value>
      <webElementGuid>c57ae7eb-7405-46fd-bdef-6aa6b6d2b282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
