<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_equip</name>
   <tag></tag>
   <elementGuidId>bba06951-8971-41aa-90a9-f976c7ad86cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss86 > div.MuiFormControl-root > div.MuiInputBase-root.MuiInput-root.MuiInput-underline.MuiInputBase-formControl.MuiInput-formControl > div.MuiSelect-root.MuiSelect-select.MuiSelect-selectMenu.MuiInputBase-input.MuiInput-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-panel']/div[2]/div/div/div[17]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '​' or . = '​')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>968a15d8-29e2-47a7-a101-ce4f5ac17da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input</value>
      <webElementGuid>33376d19-c72e-4e91-803c-0e570ef6a269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2a52f4d-b602-4854-93ac-9425913eb217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45371b29-315f-41ea-b5a9-ca007aca2878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>92b7302d-ddd5-45a9-9093-a05bab5ff87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>36a85cb4-cdc1-4879-9d89-c2361cd224c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-llYSUQ cccYGe&quot;]/div[@class=&quot;MuiBox-root jss61&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;MuiBox-root jss78&quot;]/div[@class=&quot;MuiBox-root jss85&quot;]/div[@class=&quot;MuiBox-root jss86&quot;]/div[@class=&quot;MuiFormControl-root&quot;]/div[@class=&quot;MuiInputBase-root MuiInput-root MuiInput-underline MuiInputBase-formControl MuiInput-formControl&quot;]/div[@class=&quot;MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input&quot;]</value>
      <webElementGuid>da80aca6-e894-4a36-afc6-b9706b77e6fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[17]/div/div/div/div/div</value>
      <webElementGuid>2832c4f4-97ff-4f9e-96e7-fa35f087999e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Equipment'])[1]/following::div[2]</value>
      <webElementGuid>317c49f8-9b0f-42e0-a230-645d1c0016ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment'])[1]/following::div[5]</value>
      <webElementGuid>09d87aa9-9185-4a35-a3b1-f029239fe980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[1]/preceding::div[1]</value>
      <webElementGuid>994d3171-f4e2-473c-8a50-2827b074c17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div/div/div</value>
      <webElementGuid>b53a5e5a-edd0-4ace-a5b4-358d9f2daf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '​' or . = '​')]</value>
      <webElementGuid>f6d18abd-fede-45c3-be30-f6e7f567c78d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
