<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menubar-icon</name>
   <tag></tag>
   <elementGuidId>5af5a3a4-af4b-436a-8989-adf837220d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]/div[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-bqiRlB.dKRrzd.group > div.sc-hBUSln.gDLFVM > div.sc-fotOHu.wfUoZ.icoWrap > img.rail-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>87d657aa-f15f-44f9-b83b-7d50ee41d110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>2ab731d0-36df-431b-8956-94c2bb281666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/png/budgeting.png</value>
      <webElementGuid>a0afa383-a026-442c-b89f-a60c717e4186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>51c81c4c-d80a-4667-9f7a-5cffe786a1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-kLwhqv fkRcTC&quot;]/div[@class=&quot;sc-ikJyIC biSwkQ&quot;]/div[@class=&quot;sc-bBHxTw cRwCeF&quot;]/div[@class=&quot;sc-egiyK eiYbNk&quot;]/div[3]/div[@class=&quot;sc-bqiRlB dKRrzd group&quot;]/div[@class=&quot;sc-hBUSln gDLFVM&quot;]/div[@class=&quot;sc-fotOHu wfUoZ icoWrap&quot;]/img[@class=&quot;rail-icon&quot;]</value>
      <webElementGuid>dcab8e6b-7f73-42ac-833c-24b8b4f9da19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div[4]/div/div/img</value>
      <webElementGuid>2148f324-5927-4b7b-a093-a06f31d5b4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='rail-icon']</value>
      <webElementGuid>89b692b7-8e5f-4941-a4e5-a41111571fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/img</value>
      <webElementGuid>1aef402a-9c41-4d3f-bdfb-d086503ec123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/png/budgeting.png' and @alt = 'rail-icon']</value>
      <webElementGuid>1b39a015-fcdf-40cf-a567-faff3af74173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
