<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_test_custom-form-field-text-0</name>
   <tag></tag>
   <elementGuidId>7638f9c7-19d7-43c8-8b7a-222d93cedb86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custom-form-field-text-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom-form-field-text-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2de1d293-d440-420b-84da-3498118ee5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c08d52a4-6e89-4334-9fd7-07b3a4c08454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-form-field-text-0</value>
      <webElementGuid>c1bdf330-4089-4e05-92a0-2452de8defa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f613d91-9b26-4de4-994d-ea7a5ab1a272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input</value>
      <webElementGuid>1719bed9-57a9-4685-85f9-02cfa081ab69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>§</value>
      <webElementGuid>0d0404af-1ceb-4d74-8d6f-c97e2a035f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-form-field-text-0&quot;)</value>
      <webElementGuid>b8bef0b8-857d-47ef-898e-5d414976a3f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom-form-field-text-0']</value>
      <webElementGuid>3d129be9-dcec-4a18-b61c-be14ce8070a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[14]/div/div/div/input</value>
      <webElementGuid>f905ccfd-eed4-4768-b408-290d378218c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div/input</value>
      <webElementGuid>878e0ae3-1475-4d5d-a6f7-3b441fb57fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'custom-form-field-text-0' and @type = 'text']</value>
      <webElementGuid>6abfe5ab-bf40-43be-897e-747359ce8a17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
