<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Average_condition_index</name>
   <tag></tag>
   <elementGuidId>33bd19a3-d386-4c0c-969e-61342338eecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-panel']/div[2]/div/div/div[2]/div[3]/div/div[2]/p/u</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '27.92' or . = '27.92')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>u</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>u</value>
      <webElementGuid>87faceaa-9f94-40f7-bdbf-29a114001fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mui-1406</value>
      <webElementGuid>9930c19e-99d6-42d9-a52e-04c4bd08b401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27.92</value>
      <webElementGuid>d91943ad-2595-4ec5-b0d8-af2edeaa9bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-llYSUQ cccYGe&quot;]/div[@class=&quot;MuiBox-root jss63&quot;]/div[@class=&quot;MuiBox-root jss64&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-12&quot;]/div[@class=&quot;MuiPaper-root MuiAlert-root MuiAlert-standardInfo MuiPaper-elevation0&quot;]/div[@class=&quot;MuiAlert-message&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1&quot;]/u[1]</value>
      <webElementGuid>418e2fb8-a103-4a6e-b1ad-35ffb6179793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-panel']/div[2]/div/div/div[2]/div[3]/div/div[2]/p/u</value>
      <webElementGuid>5ffb47e3-fc60-423b-90fc-c7f12e081d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load'])[1]/preceding::u[1]</value>
      <webElementGuid>f3b8d2d5-270a-4ec9-bd8b-efa6adcd07c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::u[1]</value>
      <webElementGuid>d2022958-f269-4ca2-8f2f-f7de30d818f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='27.92']/parent::*</value>
      <webElementGuid>fdd4a1e9-4805-4721-ad5a-277d563b3457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//u</value>
      <webElementGuid>21d44f61-dd84-42c4-ac9c-d711018c9e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//u[(text() = '27.92' or . = '27.92')]</value>
      <webElementGuid>bcd2b7b1-012f-40dc-aab7-6be6d4b3aaa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
