<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_You need to enable JavaScript to run t_f54555</name>
   <tag></tag>
   <elementGuidId>9779f077-47d9-4f0a-ac02-dc6756420cec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>fbbbb8c5-9906-41b6-b6dc-f04139a2287d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You need to enable JavaScript to run this app.Budget Estimatordefault scenario12 Years, Target rating 29Id1522AssetPavementDuration12 YearsTotal Budget$115,532,770Annual Inflation5%Filterpci > 0Decision TreeDT with PCI rangesTotal Repairs3,006Budget YearSummaryBudget YearViewGraphViewGraphConditionGraphCondition after 12 years: 1%ReportCloseSearchLayersWork OrdersFilterBudgetingBudget PlannerCompare ScenariosBudget EstimatorImage ViewerStreetViewMapillary ViewerEarthEditingAttribute EditorGeometry EditorSymbology EditorManagement Section EditorMoreCreate ChartsDrawDashboard Hi, Sohaib!ProfileHelpSupportLogoutLouisville, KentuckyCollapsedefault scenario - SummaryLast Year Recommended123456789101112othersHomeEnter fullscreenZoom inZoom outEsri, HERE, Garmin, SafeGraph, GeoTechnologies, Inc, METI/NASA, USGS, EPA, NPS, US Census Bureau, USDAPowered by EsriMeasurement No time-aware layers are visible id(&quot;menu-view&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root Mui-selected MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-selected&quot;]SupportSubject​Description​Add ImagesUploadCancelSendWork Order Layer SettingsShow only open work ordersShow work orders assigned to meEnable AutomationSelect LabelnoneSelect GroupAll GroupsCancelSaveSelect Work OrderGraphTable</value>
      <webElementGuid>afc912bf-69b4-4490-91a0-9d963047d879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>ac54c2d5-211e-4400-8e55-b08fd3a5d44c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>ad08e59a-d5db-495f-a72a-c289d3ee86d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'You need to enable JavaScript to run this app.Budget Estimatordefault scenario12 Years, Target rating 29Id1522AssetPavementDuration12 YearsTotal Budget$115,532,770Annual Inflation5%Filterpci > 0Decision TreeDT with PCI rangesTotal Repairs3,006Budget YearSummaryBudget YearViewGraphViewGraphConditionGraphCondition after 12 years: 1%ReportCloseSearchLayersWork OrdersFilterBudgetingBudget PlannerCompare ScenariosBudget EstimatorImage ViewerStreetViewMapillary ViewerEarthEditingAttribute EditorGeometry EditorSymbology EditorManagement Section EditorMoreCreate ChartsDrawDashboard Hi, Sohaib!ProfileHelpSupportLogoutLouisville, KentuckyCollapsedefault scenario - SummaryLast Year Recommended123456789101112othersHomeEnter fullscreenZoom inZoom outEsri, HERE, Garmin, SafeGraph, GeoTechnologies, Inc, METI/NASA, USGS, EPA, NPS, US Census Bureau, USDAPowered by EsriMeasurement No time-aware layers are visible id(&quot;menu-view&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root Mui-selected MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-selected&quot;]SupportSubject​Description​Add ImagesUploadCancelSendWork Order Layer SettingsShow only open work ordersShow work orders assigned to meEnable AutomationSelect LabelnoneSelect GroupAll GroupsCancelSaveSelect Work OrderGraphTable' or . = 'You need to enable JavaScript to run this app.Budget Estimatordefault scenario12 Years, Target rating 29Id1522AssetPavementDuration12 YearsTotal Budget$115,532,770Annual Inflation5%Filterpci > 0Decision TreeDT with PCI rangesTotal Repairs3,006Budget YearSummaryBudget YearViewGraphViewGraphConditionGraphCondition after 12 years: 1%ReportCloseSearchLayersWork OrdersFilterBudgetingBudget PlannerCompare ScenariosBudget EstimatorImage ViewerStreetViewMapillary ViewerEarthEditingAttribute EditorGeometry EditorSymbology EditorManagement Section EditorMoreCreate ChartsDrawDashboard Hi, Sohaib!ProfileHelpSupportLogoutLouisville, KentuckyCollapsedefault scenario - SummaryLast Year Recommended123456789101112othersHomeEnter fullscreenZoom inZoom outEsri, HERE, Garmin, SafeGraph, GeoTechnologies, Inc, METI/NASA, USGS, EPA, NPS, US Census Bureau, USDAPowered by EsriMeasurement No time-aware layers are visible id(&quot;menu-view&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root Mui-selected MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-selected&quot;]SupportSubject​Description​Add ImagesUploadCancelSendWork Order Layer SettingsShow only open work ordersShow work orders assigned to meEnable AutomationSelect LabelnoneSelect GroupAll GroupsCancelSaveSelect Work OrderGraphTable')]</value>
      <webElementGuid>bccfa985-4dab-41a9-88ba-c50c88b2eb68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
