<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Budgeting-icon</name>
   <tag></tag>
   <elementGuidId>283999e1-d584-469f-a2e1-0fbecb137458</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]/div[4]/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-hBUSln.gDLFVM.subWidget > div.sc-fotOHu.wfUoZ.icoWrap > img.rail-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b499e501-6aaa-43e6-a580-847743e1b06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>0c069ece-5f6d-4799-a389-643a23111bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/png/budgetPlanner.png</value>
      <webElementGuid>68683ccb-91ff-4d90-b1d4-78a86d02d6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>19329a54-ca39-446d-a97d-07be32e80a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-kLwhqv fkRcTC&quot;]/div[@class=&quot;sc-ikJyIC biSwkQ&quot;]/div[@class=&quot;sc-bBHxTw cRwCeF&quot;]/div[@class=&quot;sc-egiyK eiYbNk&quot;]/div[3]/div[@class=&quot;sc-bqiRlB dKRrzd group&quot;]/div[@class=&quot;sc-ksdxgE fEOpYo&quot;]/div[@class=&quot;sc-hBUSln gDLFVM subWidget&quot;]/div[@class=&quot;sc-fotOHu wfUoZ icoWrap&quot;]/img[@class=&quot;rail-icon&quot;]</value>
      <webElementGuid>9c06e324-afcf-4086-b2f3-d7f24f514d7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div[4]/div[2]/div/div/img</value>
      <webElementGuid>f8dcfbf4-4d00-42d8-94bb-17b705d23ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='rail-icon'])[2]</value>
      <webElementGuid>3192e7b8-493a-40de-bead-f48606131687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>3e71c3d1-1958-4a65-9194-09c8e02f6f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/png/budgetPlanner.png' and @alt = 'rail-icon']</value>
      <webElementGuid>53ed72cc-c0c8-4df6-9142-2aaf66920ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
