<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Louisville, Kentucky_esri-view-surface _e59e32</name>
   <tag></tag>
   <elementGuidId>96469bde-ee28-405d-af80-df2be2f747e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='my-container']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.esri-view-surface.esri-view-surface--inset-outline.esri-view-surface--touch-none</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>30211f1c-22af-415e-bd7a-5ea9955cedce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>esri-view-surface esri-view-surface--inset-outline esri-view-surface--touch-none</value>
      <webElementGuid>d9da3a2f-89d5-47d1-929d-7523b47dfe12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>a32b88fc-9388-4434-82e4-0bc38caf542d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29ba0f17-5ae3-440f-b7ba-69a97b7e00c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-interacting</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6f5adda0-2bcb-4c58-9024-324f93f62881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;my-container&quot;)/div[@class=&quot;esri-view-root&quot;]/div[@class=&quot;esri-view-surface esri-view-surface--inset-outline esri-view-surface--touch-none&quot;]</value>
      <webElementGuid>c788df70-0576-48c6-8572-d8befd723661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-container']/div/div</value>
      <webElementGuid>4ad804dc-8cd2-47f5-9e56-3dbc9cb6dd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Louisville, Kentucky'])[1]/following::div[5]</value>
      <webElementGuid>4ad0d0f9-14d3-43f9-8624-1ad02b132620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[11]</value>
      <webElementGuid>f4b12193-9a35-4179-918f-ece6a719ca86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collapse'])[1]/preceding::div[5]</value>
      <webElementGuid>a381185e-3ae7-4ad3-83dd-0fd34ee0153a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EBP_Inflation 7.5 - Year 1'])[1]/preceding::div[7]</value>
      <webElementGuid>86722fc4-0701-425f-bc03-2143c1692832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>0ca9ba5f-aa72-4225-9d92-8a382b5ddfb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
