<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Scenario Name_scenarioName_1</name>
   <tag></tag>
   <elementGuidId>b20214e3-e223-43e8-8e77-5f1cae9e09d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#scenarioName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='scenarioName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ea5eebd-d121-4a11-90bf-eae807fbd356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7b503423-52b7-4142-a367-ba535160070a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>scenarioName</value>
      <webElementGuid>a9b7479a-ae9f-4d27-9d7d-5d646ea83cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>089cafa6-3c22-4719-8a14-b535f7cb8be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiInput-input MuiInputBase-inputMarginDense MuiInput-inputMarginDense</value>
      <webElementGuid>4665a7f0-7ee7-4ef8-809d-4af468ca2025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>EBP_Inflation 7.5</value>
      <webElementGuid>c989191e-5df5-42a3-9458-40eeeee0fbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scenarioName&quot;)</value>
      <webElementGuid>3660941b-bbc1-42e3-9241-bcddb8f7002b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='scenarioName']</value>
      <webElementGuid>6445c347-5477-4d55-8cd2-e685b7583cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>274ea8f0-6509-46a1-953a-788c34d9a0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'scenarioName' and @type = 'text']</value>
      <webElementGuid>db38860a-13e9-410e-b070-19703b2fb71f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
