<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menubar-icon</name>
   <tag></tag>
   <elementGuidId>863c2312-8e9e-4ff7-a626-21332d10c0a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]/div[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-bqiRlB.dKRrzd.group > div.sc-hBUSln.gDLFVM > div.sc-fotOHu.wfUoZ.icoWrap > img.rail-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4dab3d07-cc1c-4aaf-ac3d-1895c085484e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>3d81c0b1-79ef-4d30-9972-043ca94de885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/png/budgeting.png</value>
      <webElementGuid>1daabf2e-6dcc-468e-a915-1e67ae3d0114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>1ad2e0f9-104a-4e5c-8a70-d1fbf32639ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-kLwhqv fkRcTC&quot;]/div[@class=&quot;sc-ikJyIC biSwkQ&quot;]/div[@class=&quot;sc-bBHxTw cRwCeF&quot;]/div[@class=&quot;sc-egiyK eiYbNk&quot;]/div[3]/div[@class=&quot;sc-bqiRlB dKRrzd group&quot;]/div[@class=&quot;sc-hBUSln gDLFVM&quot;]/div[@class=&quot;sc-fotOHu wfUoZ icoWrap&quot;]/img[@class=&quot;rail-icon&quot;]</value>
      <webElementGuid>944b2680-a39a-4393-bd2f-e7ddb1de793c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div[4]/div/div/img</value>
      <webElementGuid>2807032b-2ec9-49b7-831e-4a4f245d8cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='rail-icon']</value>
      <webElementGuid>70cc10e0-53ce-4cf8-b764-178832c044ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/img</value>
      <webElementGuid>1425d8ac-223a-45e2-b47c-cd09bcbaa681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/png/budgeting.png' and @alt = 'rail-icon']</value>
      <webElementGuid>d0093639-6dd2-4203-b030-2bc8bfe164c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
