<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Due Date_due_date</name>
   <tag></tag>
   <elementGuidId>ae01c402-cbf4-4f76-a116-102aa38cb410</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date-picker-inline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='date-picker-inline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77154962-f74b-422c-a79a-fa40f91f00d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf14ff1b-a04c-4a1e-834b-1475f30888d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date-picker-inline</value>
      <webElementGuid>b24e928a-82cf-497a-a53b-a3eab77f8cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>due_date</value>
      <webElementGuid>8accb4e4-f922-4a3e-a4cc-4cc942c8fd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd26a623-7a87-4dc6-a20c-96b4a6faa7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd</value>
      <webElementGuid>b236e191-f272-4fbd-ae21-923375a8bcaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10/19/2022</value>
      <webElementGuid>c8e454f6-1ca1-4ddb-8874-0f04641b565b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date-picker-inline&quot;)</value>
      <webElementGuid>d6a6aa09-9650-46c6-94df-e383d0580c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='date-picker-inline']</value>
      <webElementGuid>77ce9e4d-a171-4df8-95ef-f36c1d18f787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>09b38736-5a8f-4b82-8710-b5eb9a0239fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'date-picker-inline' and @name = 'due_date' and @type = 'text']</value>
      <webElementGuid>d5547fd4-f8cb-4719-af39-407d34205b01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
