<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_12 - TYLER AVE From 31ST ST To 32ND ST_2</name>
   <tag></tag>
   <elementGuidId>40c213d6-145a-4155-b7ba-7ebc5a5c287b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-48984-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-48984-option-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mui-48984-option-0' and (text() = '12 - TYLER AVE From 31ST ST To 32ND ST' or . = '12 - TYLER AVE From 31ST ST To 32ND ST')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>828cd7f2-fd55-4c8b-a706-6cb50f2a8dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>35073619-c8e2-445c-ac71-c028bc04a4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5ff8c72d-1d8d-401a-b931-0e53f616186c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-48984-option-0</value>
      <webElementGuid>a53281bd-743a-494f-95a2-295c85644ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d8ed3af5-b225-4e62-85fe-06d7410a0e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>28fbadc3-419e-4798-8da2-373095ba3564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7349d0be-a003-4822-ba77-43a2a00b185a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>ac4c86e6-abb6-485d-9ce0-fbb7da1e3e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21d74c53-3bdc-47e4-9b22-815903bae134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12 - TYLER AVE From 31ST ST To 32ND ST</value>
      <webElementGuid>6a5dfcdf-a73d-43ae-bec0-6c7d5a530b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-48984-option-0&quot;)</value>
      <webElementGuid>af79f5b4-7bdb-46a8-b627-767990dacdbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-48984-option-0']</value>
      <webElementGuid>b8bd83c3-5ad9-4920-975f-838d4bb7ad55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-48984-popup']/li</value>
      <webElementGuid>9dba5730-00a9-4539-8dae-484c1395d5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[2]/following::li[1]</value>
      <webElementGuid>9efc7db7-5349-4980-b01b-1275113139a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::li[1]</value>
      <webElementGuid>a681b9ae-969d-4f08-9bde-bedc4fed3c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12 - TYLER AVE From 31ST ST To 32ND ST']/parent::*</value>
      <webElementGuid>7bd2fa17-3f95-4679-8717-1f116f8d15be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>5e0580c6-a606-4f36-9043-511d348f03b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-48984-option-0' and (text() = '12 - TYLER AVE From 31ST ST To 32ND ST' or . = '12 - TYLER AVE From 31ST ST To 32ND ST')]</value>
      <webElementGuid>093d0bae-3376-4ea4-8ffd-ecbd2d98f5e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
