<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Priority_field</name>
   <tag></tag>
   <elementGuidId>d6aa902f-88d1-4d4a-9ada-62c42acda5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;demo-simple-select-outlined&quot;]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'priority' and @class = 'sc-hBxehG bswEeM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>51b77384-827d-4c6d-87e7-34d14673af87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You need to enable JavaScript to run this app.DashboardWork OrderService RequestWork OrdersTask CalendarCost ManagementAutomationForm LibraryAsset ManagementDecision TreeRepair PriorityDeterioration CurveRepair ImpactBatch Asset UpdateRestore EditorAdminGroupsReports Hi, Sohaib!ProfileLight ModeHelpSupportNotificationsLogoutGISWork OrdersWork Order ReportNewIn ProgressFeedback11Work OrdersNewIn ProgressNewIn ProgressFeedbackID / Form NameDispatcherAssigneeAddressResourcesCreation DateStatusPriorityTotal Cost173571Bridge MaintenanceDev AdminDev AdminTYLER AVE, Louisville, KY, USA09/29/2022New​High​173934Test Custom form will all fields assignedDemo Adminami  adminTANGELO DR From ACTON LN To DEAD ENDSnow Plow - Tontest 2 - KgAsphalt - Hrs09/29/2022In Progress​Urgent​$-1041.67173933Fix SignAsset AI UserDev UserWOODS VIEW PL, Louisville, KY, USA09/29/2022New​Low​Bridge Maintenance (16)Sohaib OwnerDev AdminMultiple Addresses (Expand to view)09/29/2022In Progress​Urgent​Bridge Maintenance (8593)Sohaib Ownerami  adminMultiple Addresses (Expand to view)10/05/2022New​Medium​182528Bridge MaintenanceDemo AdminHaseeb AnwarS WATTERSON TRL From BLEEMEL DR To GLASER LN10/07/2022New​Urgent​182529Fix SignDemo AdminHaseeb AnwarBILSIM CT From BILSIM LN To DEAD END  10/07/2022In Progress​Urgent​Bridge Maintenance (327)Asset AI UserAmi UserMultiple Addresses (Expand to view)09/29/2022New​Medium​182530Test Custom form will all fields assignedSohaib Ownerami  adminGLENDALE RD From MCKENNA WAY To GLASER LN10/18/2022New​Urgent​Test Custom form will all fields assigned (34)Sohaib Ownerami  adminMultiple Addresses (Expand to view)10/19/2022New​Medium​173605Fix SignAsset AI UserHaseeb Anwar12TH STREET CONNECTOR, Louisville, KY, USA09/29/2022New​High​Rows per page:201-11 of 11CreateSupportSubject​Description​Add ImagesUploadNo file chosenCancelSendStreetlogix performs best on Google Chrome!Switch to Chrome. Download Chrome. Don't remind me again.id(&quot;menu-priority&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss882 Mui-selected MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-selected Mui-focusVisible Mui-focusVisible&quot;]/span[@class=&quot;sc-hAZoDl kTzkdD&quot;]MajorEdit Multiple Work OrdersStatusPriorityDue DateAssigneeSaveCancelAre you sure you want to edit selected Work Order(s)?NoYesIDForm NameDispatcherAssigneeAddressStatusPriorityTotal CostSorry, no matching records foundRows per page:200-0 of 0Create a WorkorderSend Email NotificationSelect Assignee:Select AssigneeSelect AssigneeCollaboratorsami  admin​Due Date:​Priority:High​Asset ID:Search by Asset IDSearch by Asset IDAddress:Search by AddressSearch by AddressDescription:​Service Request Ids​AttachmentsUploadNo file chosenRepeating:test:​EquipmentMaterialLaborTotal:$0.00BackCreateDetailsAttachmentsCommentsCreation Date:N/ADispatcher:N/AAssignee:N/ACollaborators:N/AStatus:Priority:Due Date:N/AClosing Date:N/ALife Time:Action:N/AAsset:N/AAsset ID:N/AAddress:N/AService Request ID(s):N/AGroup:N/ARepeating:FALSEDescription:N/APrintEDITDELETEGroup FilterSelect Group​Are you sure you want to delete Work Order?NoYesAre you sure you want to delete recurring Work Orders?NoYesPrint Work OrderImagesCommentsCancelPrintUrgentHighMediumLow</value>
      <webElementGuid>31a16308-c40e-4156-9617-b72b9c1191f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>b3b02fba-fc02-4050-a527-dde9bfc162e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>High</value>
      <webElementGuid>1becbdb0-d2b7-4126-bb47-17f1b657bde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>d2b3671e-3597-4866-8726-9b8eebabc341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demo-simple-select-outlined</value>
      <webElementGuid>f95f90c8-216b-420b-bae1-608782ae376c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hBxehG bswEeM</value>
      <webElementGuid>d25907f9-2ce6-4a3d-9df8-288b322f3589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>24eaf915-709a-4941-9988-2a75e2363d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = concat(&quot;You need to enable JavaScript to run this app.DashboardWork OrderService RequestWork OrdersTask CalendarCost ManagementAutomationForm LibraryAsset ManagementDecision TreeRepair PriorityDeterioration CurveRepair ImpactBatch Asset UpdateRestore EditorAdminGroupsReports Hi, Sohaib!ProfileLight ModeHelpSupportNotificationsLogoutGISWork OrdersWork Order ReportNewIn ProgressFeedback11Work OrdersNewIn ProgressNewIn ProgressFeedbackID / Form NameDispatcherAssigneeAddressResourcesCreation DateStatusPriorityTotal Cost173571Bridge MaintenanceDev AdminDev AdminTYLER AVE, Louisville, KY, USA09/29/2022New​High​173934Test Custom form will all fields assignedDemo Adminami  adminTANGELO DR From ACTON LN To DEAD ENDSnow Plow - Tontest 2 - KgAsphalt - Hrs09/29/2022In Progress​Urgent​$-1041.67173933Fix SignAsset AI UserDev UserWOODS VIEW PL, Louisville, KY, USA09/29/2022New​Low​Bridge Maintenance (16)Sohaib OwnerDev AdminMultiple Addresses (Expand to view)09/29/2022In Progress​Urgent​Bridge Maintenance (8593)Sohaib Ownerami  adminMultiple Addresses (Expand to view)10/05/2022New​Medium​182528Bridge MaintenanceDemo AdminHaseeb AnwarS WATTERSON TRL From BLEEMEL DR To GLASER LN10/07/2022New​Urgent​182529Fix SignDemo AdminHaseeb AnwarBILSIM CT From BILSIM LN To DEAD END  10/07/2022In Progress​Urgent​Bridge Maintenance (327)Asset AI UserAmi UserMultiple Addresses (Expand to view)09/29/2022New​Medium​182530Test Custom form will all fields assignedSohaib Ownerami  adminGLENDALE RD From MCKENNA WAY To GLASER LN10/18/2022New​Urgent​Test Custom form will all fields assigned (34)Sohaib Ownerami  adminMultiple Addresses (Expand to view)10/19/2022New​Medium​173605Fix SignAsset AI UserHaseeb Anwar12TH STREET CONNECTOR, Louisville, KY, USA09/29/2022New​High​Rows per page:201-11 of 11CreateSupportSubject​Description​Add ImagesUploadNo file chosenCancelSendStreetlogix performs best on Google Chrome!Switch to Chrome. Download Chrome. Don&quot; , &quot;'&quot; , &quot;t remind me again.id(&quot;menu-priority&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss882 Mui-selected MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-selected Mui-focusVisible Mui-focusVisible&quot;]/span[@class=&quot;sc-hAZoDl kTzkdD&quot;]MajorEdit Multiple Work OrdersStatusPriorityDue DateAssigneeSaveCancelAre you sure you want to edit selected Work Order(s)?NoYesIDForm NameDispatcherAssigneeAddressStatusPriorityTotal CostSorry, no matching records foundRows per page:200-0 of 0Create a WorkorderSend Email NotificationSelect Assignee:Select AssigneeSelect AssigneeCollaboratorsami  admin​Due Date:​Priority:High​Asset ID:Search by Asset IDSearch by Asset IDAddress:Search by AddressSearch by AddressDescription:​Service Request Ids​AttachmentsUploadNo file chosenRepeating:test:​EquipmentMaterialLaborTotal:$0.00BackCreateDetailsAttachmentsCommentsCreation Date:N/ADispatcher:N/AAssignee:N/ACollaborators:N/AStatus:Priority:Due Date:N/AClosing Date:N/ALife Time:Action:N/AAsset:N/AAsset ID:N/AAddress:N/AService Request ID(s):N/AGroup:N/ARepeating:FALSEDescription:N/APrintEDITDELETEGroup FilterSelect Group​Are you sure you want to delete Work Order?NoYesAre you sure you want to delete recurring Work Orders?NoYesPrint Work OrderImagesCommentsCancelPrintUrgentHighMediumLow&quot;) or . = concat(&quot;You need to enable JavaScript to run this app.DashboardWork OrderService RequestWork OrdersTask CalendarCost ManagementAutomationForm LibraryAsset ManagementDecision TreeRepair PriorityDeterioration CurveRepair ImpactBatch Asset UpdateRestore EditorAdminGroupsReports Hi, Sohaib!ProfileLight ModeHelpSupportNotificationsLogoutGISWork OrdersWork Order ReportNewIn ProgressFeedback11Work OrdersNewIn ProgressNewIn ProgressFeedbackID / Form NameDispatcherAssigneeAddressResourcesCreation DateStatusPriorityTotal Cost173571Bridge MaintenanceDev AdminDev AdminTYLER AVE, Louisville, KY, USA09/29/2022New​High​173934Test Custom form will all fields assignedDemo Adminami  adminTANGELO DR From ACTON LN To DEAD ENDSnow Plow - Tontest 2 - KgAsphalt - Hrs09/29/2022In Progress​Urgent​$-1041.67173933Fix SignAsset AI UserDev UserWOODS VIEW PL, Louisville, KY, USA09/29/2022New​Low​Bridge Maintenance (16)Sohaib OwnerDev AdminMultiple Addresses (Expand to view)09/29/2022In Progress​Urgent​Bridge Maintenance (8593)Sohaib Ownerami  adminMultiple Addresses (Expand to view)10/05/2022New​Medium​182528Bridge MaintenanceDemo AdminHaseeb AnwarS WATTERSON TRL From BLEEMEL DR To GLASER LN10/07/2022New​Urgent​182529Fix SignDemo AdminHaseeb AnwarBILSIM CT From BILSIM LN To DEAD END  10/07/2022In Progress​Urgent​Bridge Maintenance (327)Asset AI UserAmi UserMultiple Addresses (Expand to view)09/29/2022New​Medium​182530Test Custom form will all fields assignedSohaib Ownerami  adminGLENDALE RD From MCKENNA WAY To GLASER LN10/18/2022New​Urgent​Test Custom form will all fields assigned (34)Sohaib Ownerami  adminMultiple Addresses (Expand to view)10/19/2022New​Medium​173605Fix SignAsset AI UserHaseeb Anwar12TH STREET CONNECTOR, Louisville, KY, USA09/29/2022New​High​Rows per page:201-11 of 11CreateSupportSubject​Description​Add ImagesUploadNo file chosenCancelSendStreetlogix performs best on Google Chrome!Switch to Chrome. Download Chrome. Don&quot; , &quot;'&quot; , &quot;t remind me again.id(&quot;menu-priority&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss882 Mui-selected MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button Mui-selected Mui-focusVisible Mui-focusVisible&quot;]/span[@class=&quot;sc-hAZoDl kTzkdD&quot;]MajorEdit Multiple Work OrdersStatusPriorityDue DateAssigneeSaveCancelAre you sure you want to edit selected Work Order(s)?NoYesIDForm NameDispatcherAssigneeAddressStatusPriorityTotal CostSorry, no matching records foundRows per page:200-0 of 0Create a WorkorderSend Email NotificationSelect Assignee:Select AssigneeSelect AssigneeCollaboratorsami  admin​Due Date:​Priority:High​Asset ID:Search by Asset IDSearch by Asset IDAddress:Search by AddressSearch by AddressDescription:​Service Request Ids​AttachmentsUploadNo file chosenRepeating:test:​EquipmentMaterialLaborTotal:$0.00BackCreateDetailsAttachmentsCommentsCreation Date:N/ADispatcher:N/AAssignee:N/ACollaborators:N/AStatus:Priority:Due Date:N/AClosing Date:N/ALife Time:Action:N/AAsset:N/AAsset ID:N/AAddress:N/AService Request ID(s):N/AGroup:N/ARepeating:FALSEDescription:N/APrintEDITDELETEGroup FilterSelect Group​Are you sure you want to delete Work Order?NoYesAre you sure you want to delete recurring Work Orders?NoYesPrint Work OrderImagesCommentsCancelPrintUrgentHighMediumLow&quot;))]</value>
      <webElementGuid>bd44d8c6-c82c-4558-a216-0cd38de21196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
