<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Medium</name>
   <tag></tag>
   <elementGuidId>5d662220-f916-4e40-84ea-509775845edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.sc-hAZoDl.iLVueQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[13]/div[3]/ul/li[3]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'priority' and @class = 'sc-hBxehG kbXcpj' and (text() = 'Medium' or . = 'Medium')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c8b4714b-0ea6-45cf-8586-5c1b1fbbf985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>63c75038-5996-4b7e-b1b7-9d0a957cb37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hBxehG kbXcpj</value>
      <webElementGuid>ab087b10-2744-4002-943e-f341661c0c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medium</value>
      <webElementGuid>8d16f80f-eeea-4aa7-9eb7-77213a4f6457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-priority&quot;)/div[@class=&quot;MuiPaper-root MuiMenu-paper MuiPopover-paper MuiPaper-elevation8 MuiPaper-rounded&quot;]/ul[@class=&quot;MuiList-root MuiMenu-list MuiList-padding&quot;]/li[@class=&quot;MuiButtonBase-root MuiListItem-root MuiMenuItem-root jss882 MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button&quot;]/span[@class=&quot;sc-hAZoDl iLVueQ&quot;]</value>
      <webElementGuid>e32cf297-fc16-4142-a890-0878a04810a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@type='priority'])[16]</value>
      <webElementGuid>6ef42cd1-e323-41a2-8ef9-cc4a744020bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-priority']/div[3]/ul/li[3]/span</value>
      <webElementGuid>bfd3b8e2-4d02-4ff2-ad47-81ac035a4294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='High'])[4]/following::span[2]</value>
      <webElementGuid>ba847641-50eb-449a-9e90-b1a44631c4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urgent'])[6]/following::span[4]</value>
      <webElementGuid>4bc5c155-8abb-41f9-b4c0-6fec37023169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low'])[2]/preceding::span[4]</value>
      <webElementGuid>497d7b79-e0e4-4c30-83ea-24ae2050e388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/span</value>
      <webElementGuid>132e7b14-d686-4d62-9504-6b9d1460ac9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'priority' and (text() = 'Medium' or . = 'Medium')]</value>
      <webElementGuid>bcda19b1-4544-4d93-b9af-95f597935148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
