<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dev Admin</name>
   <tag></tag>
   <elementGuidId>58cea863-18c1-4fa1-875f-1621f34c4b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combo-box-demo-option-0 > div.sc-ezWOiH.jCxHJa > span.image-cell-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='combo-box-demo-option-0']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb936999-3096-4452-8686-77c0154a12c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-cell-text</value>
      <webElementGuid>e473ff36-64cc-4389-83c4-9938370d76fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dev Admin</value>
      <webElementGuid>116ddc1b-2204-4660-95c3-eed4c998fca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combo-box-demo-option-0&quot;)/div[@class=&quot;sc-ezWOiH jCxHJa&quot;]/span[@class=&quot;image-cell-text&quot;]</value>
      <webElementGuid>63068c62-5744-4e12-9d46-f312c8c5a0b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='combo-box-demo-option-0']/div/span</value>
      <webElementGuid>f3ce0f43-7a11-4d8c-a94c-5bc1d230d6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[2]/following::span[2]</value>
      <webElementGuid>b01f0112-1344-4286-9569-4c3fc4393a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::span[4]</value>
      <webElementGuid>27d9f81a-a377-49c9-9001-649804d85d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::span[1]</value>
      <webElementGuid>8eb11a59-5540-487f-a91a-198d6a656454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/span</value>
      <webElementGuid>1349b653-3a36-4f57-bc53-dd139535d502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dev Admin' or . = 'Dev Admin')]</value>
      <webElementGuid>0409753f-3896-417f-9fde-8b69d7d540b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
