<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>4f74ec33-d404-4c00-a24b-968330466852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>bce57901-ff65-4d77-ac83-51603ef9bd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>bcc1712f-1bf7-4236-b2fb-841479472be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>841084a5-0911-44d6-943a-07ca5d5e008e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>f5d5c22f-c99b-4bd8-842c-ba1cf5682179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-panel&quot;)/div[@class=&quot;sc-llYSUQ cccYGe&quot;]/div[@class=&quot;MuiBox-root jss60&quot;]/div[@class=&quot;MuiBox-root jss61&quot;]/div[@class=&quot;jss56&quot;]/div[@class=&quot;jss57&quot;]/div[@class=&quot;MuiBox-root jss62&quot;]/div[@class=&quot;jss63&quot;]/div[@class=&quot;jss64&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root jss65  MuiIconButton-sizeSmall&quot;]/span[@class=&quot;MuiIconButton-label&quot;]/svg[@class=&quot;MuiSvgIcon-root jss66&quot;]/circle[1]</value>
      <webElementGuid>f9ba8069-d736-4f19-8d0d-73230f84f4f8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
