<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search_rail-icon</name>
   <tag></tag>
   <elementGuidId>cc2be1df-a9ea-481b-b590-3ee9b2a79b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rail-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9e014803-e853-405a-9cf8-88caac3a9b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rail-icon</value>
      <webElementGuid>296714fb-d90d-4e03-be60-9246f35ccc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/png/layerList.png</value>
      <webElementGuid>95e97de4-495a-4609-8294-ce43b84c568b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>03b51f95-a4b2-4252-9b81-964d02a92ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-kLwhqv fkRcTC&quot;]/div[@class=&quot;sc-ikJyIC biSwkQ&quot;]/div[@class=&quot;sc-bBHxTw cRwCeF&quot;]/div[@class=&quot;sc-egiyK eiYbNk&quot;]/div[3]/div[@class=&quot;sc-hBUSln gDLFVM widget&quot;]/div[@class=&quot;sc-fotOHu wfUoZ icoWrap&quot;]/img[@class=&quot;rail-icon&quot;]</value>
      <webElementGuid>9f3b88d3-fd50-47a5-8480-824152f18869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/img</value>
      <webElementGuid>3ae5e90d-4c01-4e16-8cfa-cb749f4c2662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon']</value>
      <webElementGuid>b019faec-1951-46ef-a140-0889c02b7851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a3f7cc4d-1647-4f2e-9fa4-16cb3aefd7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/png/layerList.png' and @alt = 'icon']</value>
      <webElementGuid>58b88527-a396-4fbc-9810-c9b6415aa80e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
